/*
 * Copyright 2014 EUROPEAN DYNAMICS SA <info@eurodyn.com>
 *
 * Licensed under the EUPL, Version 1.1 only (the "License").
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 */
package com.eurodyn.qlack2.fuse.imaging.impl.model;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Query;
import javax.persistence.Table;

/**
 * ImgImageAttribute generated by hbm2java
 */
@Entity
@Table(name = "img_image_attribute")
public class ImageAttribute {

	@Id
	private String id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "image_id")
	private Image imageId;
	private String name;
	private String value;

	public ImageAttribute() {
		id = java.util.UUID.randomUUID().toString();
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Image getImageId() {
		return this.imageId;
	}

	public void setImageId(Image imageId) {
		this.imageId = imageId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}
	
	public static ImageAttribute findByNameAndImageID(EntityManager em, String name, String imageID) {
		Query q = em
				.createQuery("SELECT a FROM ImageAttribute a WHERE a.name = :name AND a.imageId.id = :id");
		q.setParameter("name", name);
		q.setParameter("id", imageID);
		List<ImageAttribute> resultList = q.getResultList();
		return (resultList.isEmpty()) ? null : resultList.get(0);
	}

}
